name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Increase patch version
        id: increase_version
        run: |
          echo "Updating patch version..."
          CURRENT_VERSION=$(grep -oP '(?<=<version>)[0-9]+\.[0-9]+\.[0-9]+(?=-SNAPSHOT</version>)' myapp/pom.xml)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          sed -i "s/<version>$CURRENT_VERSION-SNAPSHOT<\/version>/<version>$NEW_VERSION-SNAPSHOT<\/version>/" myapp/pom.xml
          echo "New version: $NEW_VERSION"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Compile the code
        run: mvn -f myapp/pom.xml clean compile

      - name: Package the application
        run: mvn -f myapp/pom.xml package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp-jar
          path: myapp/target/*.jar

      - name: Build Docker image with non-root user
        run: |
          echo "Building Docker image with non-root user..."
          echo "FROM maven:3.9.9-amazoncorretto-17-al2023 AS build" > Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY myapp/pom.xml ./" >> Dockerfile
          echo "RUN mvn dependency:go-offline -B" >> Dockerfile
          echo "COPY myapp/src ./src" >> Dockerfile
          echo "RUN mvn clean package -DskipTests" >> Dockerfile
          echo "FROM amazoncorretto:17-alpine" >> Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "RUN addgroup -S mygroup && adduser -S myuser -G mygroup" >> Dockerfile
          echo "USER myuser" >> Dockerfile
          echo "COPY --from=build /app/target/myapp-${{ env.VERSION }}-SNAPSHOT.jar /app/app.jar" >> Dockerfile
          echo "CMD [\"java\", \"-jar\", \"/app/app.jar\"]" >> Dockerfile
          docker build -t myapp:${{ env.VERSION }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker tag myapp:${{ env.VERSION }} ${{ secrets.DOCKER_HUB_USERNAME }}/maven-hello-world:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/maven-hello-world:${{ env.VERSION }}

      - name: Pull and Run Docker image
        run: |
          echo "Running Docker image..."
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/maven-hello-world:${{ env.VERSION }}
          docker run -d -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/maven-hello-world:${{ env.VERSION }}